name: cupertino_progress_bar_example
description: CupertinoProgressBar for Flutter example app.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_progress_bar:
    path: ../
  flutter:
    sdk: flutter
