name: cupertino_progress_bar
description: >-
  A non-interactive progress bar includes a track that fills from left to right to show the
  progression of a task with a known duration.
version: 0.1.0
homepage: https://github.com/jpnurmi/cupertino_progress_bar
repository: https://github.com/jpnurmi/cupertino_progress_bar
issue_tracker: https://github.com/jpnurmi/cupertino_progress_bar/issues

environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
